

CREATE TABLE public.question (
	id serial4 NOT NULL,
	question_title varchar(255) NULL,
	option1 varchar(255) NULL,
	option2 varchar(255) NULL,
	option3 varchar(255) NULL,
	option4 varchar(255) NULL,
	right_answer varchar(255) NULL,
	difficultylevel varchar(255) NULL,
	category varchar(255) NULL,
	CONSTRAINT question_pkey PRIMARY KEY (id)
);

CREATE TABLE public.quiz (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title varchar(255) NULL,
	CONSTRAINT quiz_pkey PRIMARY KEY (id)
);

CREATE TABLE public.quiz_question_ids (
	quiz_id int4 NOT NULL,
	question_ids int4 NULL
);


-- public.quiz_question_ids foreign keys

ALTER TABLE public.quiz_question_ids ADD CONSTRAINT quiz_question_ids_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


